#############################################################################
# Makefile for building: libPVRTexLibWrapper.so
#############################################################################

first: all

####### Build rules

all:
	cd x86 && make && cd ..
	cd x64 && make && cd ..

clean:
	cd x86 && make clean && cd ..
	cd x64 && make clean && cd ..

